language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
after_script:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "jnBd9bQaluqZxAAPBVLVT0Fe604WM2y6/rcZ00655B0pQyy9mQYnVOPvMbqmhmhmW9B37TO5ynbG6RhRuNQm7B3D4DPqP0cyGMPBbvqMnpcd+njFtgLN04ejABQ9BAdC/YEc3TopBHMaVg3Ge9yQxpogxTVk3aADjpiVxbsGZeH3IYCR+qUF2AunegD8shs2B8f5eG/o+n41M+PkvjfEI/4SOWsEwjRmeLbOaoCK02ZpVzBwRbCr3eWCKuosFa8PW0R0SC4u+hPY6aOjjaH9ZbbdP4Ze3/mB/nfdnNCiYrdwtdPpoKNzv+46blOCj1dfiWe51ndtGnhfkIVirBWf0Td9DZx7ksvV35PyeD/An+Dz2EqNqrXBADWbY3HfsZPsxwLkYSXZS6v8z8nDBDatEO55yu0PIzI9Pn1ZKj0KY9DDddrshj+VbWN4TeYS8ibcxGJUeEBdlOsAIwQN5QiBbmtKdcl7sZ0KnaTSRcVNI7kpB+RfWnMMHugcEh092fqJhe7JI2HYFqvqp6eUk/rNCkBCeMD6wNb/Vmo0LThsx8fmi4vAjhfqLlChjcFAd7dNKDBgpNFwGrw2u2x3DRASC4Nwi3lDrUzKa7Fj5y3H1AntS4iIiT7gA7bGPuH0RC0gpB/U7tKR7KAsqtDE8zqfjl6NppdaWZ35DrlKkewxmpo="